name: fullymobile
channels:
  - defaults
dependencies:
    - numpy
    - matplotlib
    - pandas
    - scipy
    - seaborn
    - pip
    - jupyter
    - tqdm
    - pip:
          - EoN
          - ortools
          - geopy
